#!/bin/sh
### BEGIN INIT INFO
# Provides:          iofabric
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop iofabric server
### END INIT INFO
 
JAR_FILE_NAME=$PATH_TO_JAR/$SERVICE_NAME.jar

case $1 in
    start)
	echo "Starting iofabric service..."
        cd $PATH_TO_JAR
        sudo java -jar $JAR_FILE_NAME start &
    ;;
    stop)
        cd $PATH_TO_JAR
        sudo java -jar $JAR_FILE_NAME stop
    ;;
    restart)
	echo "Restarting iofabric service..."
        cd $PATH_TO_JAR
        sudo java -jar $JAR_FILE_NAME stop
        sudo java -jar $JAR_FILE_NAME start &
    ;;
esac


